src/blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'
urlpatterns = [
    path('articles/', views.articles, name='articles'),
    path('articles/<int:pk>/', views.article_details, name='details')
]

src/portfolio/urls.py
from django.urls import path
from . import views


app_name = 'portfolio'
urlpatterns = [
    path('projects/', views.projects, name='projects')
]

src/simple_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('portfolio/', include('portfolio.urls', namespace='portfolio')),
    path('blog/', include('blog.urls', namespace='blog'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/blog/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=140)
    description = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

src/portfolio/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=144)
    description = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

src/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Article


def articles(request):
    articles = Article.objects.order_by('-date')
    return render(request, 'blog/index.html', {'articles': articles})


def article_details(request, pk):
    article = get_object_or_404(Article, pk=pk)
    return render(request, 'blog/article_details.html', {'article': article})

src/portfolio/views.py
from django.shortcuts import render
from .models import Project


def projects(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/index.html', {'projects': projects})

src/simple_blog/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Simple Blog{% endblock %}</title>
    <link rel="shortcut icon" href="{% static '/img/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static '/img/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% url 'index' as index %}

    {% block content %}
    {% endblock %}

    {% if request.path != index %}
        {% include 'snippets/back_to_home.html' %}
    {% endif %}
</body>
</html>

src/templates/blog/article_details.html
{% extends 'base.html' %}

{% block title %}{{ article.title }} at Simple Blog{% endblock %}

{% block content %}
<h1>{{ article.title }}</h1>
<p><small>{{ article.date }}</small></p>
<p>{{ article.description }}</p>
<hr/>
<a href="{% url 'blog:articles' %}">volver a todos los articulos</a>
{% endblock %}

src/templates/blog/index.html
{% extends 'base.html' %}

{% block content %}
    <p>Se han escrito {{ articles.count }} articulo{{ articles.count|pluralize }}</p>

    {% for article in articles %}
    <h3><a href="{% url 'blog:details' article.pk %}">{{ article.title|upper }}</a></h3>
    <p><small>{{ article.date|date:'M d Y' }}</small></p>
    <p>{{ article.description|truncatechars:100 }}</p>
    <hr/>
    {% endfor %}
{% endblock %}

src/templates/index.html
{% extends 'base.html' %}

{% block content %}
<a href="{% url 'portfolio:projects' %}">Ver proyectos</a>
<a href="{% url 'blog:articles' %}">Ver articulos</a>
{% endblock %}

src/templates/portfolio/index.html
{% extends 'base.html' %}

{% block content %}
    {% for project in projects %}
    <p>{{ project.title }}</p>
    <img src="{{ project.image.url }}" alt="project image" width="60">
    <hr/>
    {% endfor %}
{% endblock %}

src/templates/snippets/back_to_home.html
<p>
  <a href="{% url 'index' %}">volver a inicio</a>
</p>